xsos: Add new functionality to display the ARP table from procfs.
Signed-off-by: Mithil Mhatre <mithilmhatre92@gmail.com>

diff --git a/xsos b/xsos
--- a/xsos
+++ b/xsos
@@ -1,5 +1,5 @@
 #!/bin/bash
-# xsos v0.7.41 last mod 2026-05-28
+# xsos v0.7.42 last mod 2026-06-12
 # Latest version at <http://github.com/ryran/xsos>
 # Copyright 2012-2026 Ryan Sawhill Aroha <rsaw@redhat.com> and contributors
 #
@@ -117,7 +117,7 @@ fi
 
 # XSOS_ALL_VIEW (str of variables, space-separated)
 #   Controls what content modules to run when -a/--all switch is used
-    : ${XSOS_ALL_VIEW:="bios os kdump cpu intrupt mem disks mpath lspci ethtool softirq bonding ip netdev sysctl ps ss firewall"}
+    : ${XSOS_ALL_VIEW:="bios os kdump cpu intrupt mem disks mpath lspci ethtool softirq bonding ip netdev sysctl ps ss firewall arp"}
 
 # XSOS_DEFAULT_VIEW (str of variables, space-separated)
 #   Controls default content modules, i.e. what to run when none are specififed
@@ -219,7 +219,7 @@ See <github.com/ryran/xsos> to report bugs or suggestions"
 }
 
 HELP_USAGE() {
-  echo "Usage: xsos [DISPLAY OPTIONS] [-6abokcfmdtlerngispSFIN] [SOSREPORT ROOT]
+  echo "Usage: xsos [DISPLAY OPTIONS] [-6abokcfmdtlerngispSFINA] [SOSREPORT ROOT]
   or:  xsos [DISPLAY OPTIONS] {--B|--C|--F|--M|--D|--T|--L|--R|--N|--G|--I|--P FILE}...
   or:  xsos [-?|-h|--help]
 
@@ -245,12 +245,13 @@ Content options:"
  -n, --netdev❚show info from /proc/net/dev
  -g, --bonding❚show bonding and teaming info
  -i, --ip❚show info from ip addr (BASH v4+ required)
-     --net❚alias for: --lspci --ethtool --softirq --netdev --bonding --ip
+     --net❚alias for: --lspci --ethtool --softirq --netdev --bonding --ip --arp
  -s, --sysctl❚show important kernel sysctls
  -p, --ps❚inspect running processes via ps
  -S, --ss❚inspect running processes via ss
  -F, --firewall❚show firewall status
  -I, --ifcfg❚show ifcfg files summary
+ -A, --arp❚show info from /proc/net/arp
  -N, --netstat❚show info from /proc/net/netstat" | column -ts❚
 }
 
@@ -369,8 +370,8 @@ case $1 in
 esac
 
 # GNU getopt short and long options:
-sopts='6q:u:v:w:xyzabokcfmdtlerngispSFIN'
-lopts='scrub,ipv6,rhsupport,wwid:,unit:,threads,verbose:,width:,nocolor,less,more,all,bios,os,kdump,cpu,intrupt,mem,disks,mpath,lspci,ethtool,softirq,netdev,bonding,ip,net,sysctl,ps,ss,firewall,ifcfg,netstat,B:,C:,F:,M:,D:,T:,L:,R:,N:,G:,I:,P:'
+sopts='6q:u:v:w:xyzabokcfmdtlerngispSFINA'
+lopts='scrub,ipv6,rhsupport,wwid:,unit:,threads,verbose:,width:,nocolor,less,more,all,bios,os,kdump,cpu,intrupt,mem,disks,mpath,lspci,ethtool,softirq,netdev,bonding,ip,net,sysctl,ps,ss,firewall,ifcfg,netstat,arp,B:,C:,F:,M:,D:,T:,L:,R:,N:,G:,I:,P:'
 
 # Check for bad switches
 getopt -Q --name=xsos -o $sopts -l $lopts -- "$@" || { HELP_USAGE; exit 64; }
@@ -423,7 +424,7 @@ _OPT_CHECK() {
 
 # Parse command-line arguments
 PARSE() {
-  unset opts all bios os kdump cpu intrupt mem disks mpath lspci ethtool softirq netdev bonding ip net sysctl ps
+  unset opts all bios os kdump cpu intrupt mem disks mpath lspci ethtool softirq netdev bonding ip net sysctl ps arp
   until [[ $1 == -- ]]; do
     case $1 in
       --scrub)      XSOS_SCRUB_IP_HN=y XSOS_SCRUB_MACADDR=y XSOS_SCRUB_SERIAL=y XSOS_SCRUB_PROXYUSERPASS=y ;;
@@ -446,6 +447,7 @@ PARSE() {
       -z|--more)    XSOS_OUTPUT_HANDLER='more'     ;;
       --rhsupport)  XSOS_OS_RHT_CENTRIC=y          ;;
       -a|--all)     opts=y all=y     ;;
+      -A|--arp)     opts=y arp=y     ;;
       -b|--bios)    opts=y bios=y    ;;
       -o|--os)      opts=y os=y      ;;
       -k|--kdump)   opts=y kdump=y   ;;
@@ -466,7 +468,7 @@ PARSE() {
       -F|--firewall)opts=y firewall=y ;;
       -I|--ifcfg)   opts=y ifcfg=y   ;;
       -N|--netstat) opts=y netstat=y ;;
-      --net)        opts=y lspci=y ethtool=y softirq=y netdev=y ip=y firewall=y bonding=y teaming=y ss=y ifcfg=y netstat=y ;;
+      --net)        opts=y lspci=y ethtool=y softirq=y netdev=y ip=y firewall=y bonding=y teaming=y ss=y ifcfg=y netstat=y arp=y ;;
       
       --B)  sfile[B]=$2; shift ;;
       --F)  sfile[F]=$2; shift ;;
@@ -3907,6 +3909,32 @@ NETSTAT(){
   
 }
 
+ARP() {
+  # Local vars:
+  local arp_input_file
+
+  [[ -f $1 ]] && arp_input_file=$1 || arp_input_file=$1/proc/net/arp
+
+  echo -e "${c[H1]}ARP${c[0]}"
+
+  # Check if file exists and is not empty
+  if [[ ! -f "$arp_input_file" ]]; then
+    echo "${XSOS_INDENT_H1}File not found: $arp_input_file" >&2
+    return 1
+  fi
+
+  # Skip header line and format output
+  tail -n+2 "$arp_input_file" | gawk -v indent="$XSOS_INDENT_H1" '
+    BEGIN {
+      printf "%s%-18s %-8s %-8s %-19s %-8s %s\n", indent, "IP address", "HW type", "Flags", "HW address", "Mask", "Device"
+    }
+    {
+      # Fields: IP address, HW type, Flags, HW address, Mask, Device
+      printf "%s%-18s %-8s %-8s %-19s %-8s %s\n", indent, $1, $2, $3, $4, $5, $6
+    }
+  '
+}
+
 #-------------------------------------------------------------------------------
 # BLEH
 # Eventually I'll probably replace all of this with a python loader.
@@ -4016,7 +4044,8 @@ trap "rm -rf $TMPDIR 2>/dev/null" EXIT
     SOS_CHECKFILE firewall "sos_commands/systemd/systemctl_status_--all" && FIREWALL   "$sosroot"
     SOS_CHECKFILE ifcfg   "etc/sysconfig/network-scripts"      && IFCFG     "$sosroot"
     SOS_CHECKFILE netstat "/proc/net/netstat"                  && NETSTAT   "$sosroot"
-    
+    SOS_CHECKFILE arp     "proc/net/arp"                       && ARP       "$sosroot"
+
   # If no SOSREPORT-ROOT provided, run checks against local system
   else
     [[ -n $bios ]]    && COND_RUN dmidecode --require_root
@@ -4041,6 +4070,7 @@ trap "rm -rf $TMPDIR 2>/dev/null" EXIT
     [[ -n $firewall ]]&& FIREWALL
     [[ -n $ifcfg ]]   && IFCFG
     [[ -n $netstat ]] && NETSTAT
+    [[ -n $arp ]]     && ARP
 
   fi
   
